### PR TITLE
Run after suspend-then-hibernate

### PR DESCRIPTION
**Pull request by agura-lex**
**Description**
After hibernating via systemd's suspend-then-hibernate (for example, some old versions of Gnome do that by default) `asus-fan-control` is not being run, which results in resetting fan speed values to the default ones. It appears that `suspend-then-hibernate.target` in systemd is not bound to `hibernate.target`, so we need both of them in our systemd unit which is run on resume.

### CODE REVIEW

**Comment by agura-lex** [comment]
`After=` in `[Unit]` means that it's run after the desired unit. It could be just a space-separated list, but having it line-by-line seems more readable to me, but no strong opinion on that, so I can change it if you like it more that way. Doc: https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Before=

`WantedBy=` in `[Install]` section means that if your unit gets enabled, it'll be enabled to run as a dependency for the specified unit. Doc: https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Before=

And yes, I did test it.

**Comment by dominiksalvet** [comment]
Thank you for the explanation. I had already seen a documentation about the options by the time of writing previous comment but I was a bit confused.

To be honest, I am confused right now as well... Are both options really required? Aren't both options the same? What would happen if one of them gets removed? You don't have to answer my questions, you are the systemd maintainer, so I trust you. I am just curious... xD

I prefer the single-line in this case as it seems to be more simple and it looks more readable for me. The distraction I see is two lines unnecessarily starting with the same words. It could even take a bit of time to figure out whether it is a re-definition or adding items to a list...

**Comment by agura-lex** [comment]
I tried removing `After=` directive and it just wouldn't run when I expect it to. And removing `WantedBy=` makes it useless since it's not installed by `systemctl enable` (`[Install]` section is all about that) as it requires `WantedBy=`. 

BTW, I just realized I sent two identical links to the docs, edited the second one.

**Comment by agura-lex** [comment]
TBH, all that systemd syntax is kinda complicated, I'm just using the simplest solutions I can google and then read the doc to have some understanding of what I'm doing. xD

**Comment by dominiksalvet** [comment]
Thank you so much for another contribution! :heart:

Just a note: this change is practically already included in the *CHANGELOG.md* file since #15 merged and so it needn't be updated. We have only improved things to work better... :rocket:

**Comment by dominiksalvet** [comment]
BTW, is it possible to merge *asus-fan-control.service* and *asus-fan-control-resume.service* files?

**Comment by agura-lex** [comment]
>Just a note: this change is practically already included in the CHANGELOG.md file since #15 merged and so it needn't be updated

Yeah, that's why I haven't updated it. I could just forget to though. :D

>BTW, is it possible to merge asus-fan-control.service and asus-fan-control-resume.service files? 🤔

Thought about that, but don't remember what stopped me. But trying to merge 'em is in my backlog. I guess, it's just a matter of adding needed dependencies to the main `.service`, needs a tiny bit of research and testing, but I think it should work.

**Comment by agura-lex** [comment]
I'll try to do that this evening if I've got enough time to. Want to sort that out before next release.

**Comment by dominiksalvet** [comment]
Yeah, feel free to **push it directly** to the master branch.

I am currently working on the [new-api](https://github.com/dominiksalvet/asus-fan-control/tree/new-api) branch, so there should be no conflict at all. Once you push the changes to master, I will fetch them to new-api.

BTW, I want the changes of new-api to be present in the next release as well. Feel free to take a look on new-api once a while whether you like the new API. Maybe I will create a PR draft once there is enough changes to discuss them.

**Comment by dominiksalvet** [comment]
Just a note: the master branch is protected and it prevents from direct pushes to it. I have completely forgotten about it. So creating a PR is the way.

Sorry for any inconvenience caused.

**Pull request merged**
