### PR TITLE
New API

### PR DESCRIPTION
**Pull request by dominiksalvet**
**Description**
The current upstream API is not as simple as it can be. This PR remasters the whole API to make it more simple and intuitive. Also, the code quality, namely its robustness, has been significantly increased.

The most notable changes are:

* Removed support for batch arguments (multiple options processing sequentially)
* `-set-temps:<numbers>` option has been changed to `set-temps TEMPERATURES` command
* `-set-default-temps` option can be substituted by `set-temps default` command
* `-help` option has been changed to `help` command (use it for more information)

**Additional context**
The asus-fan-control file structure has been altered appropriately as well. Also, MD files have been updated to reflect the changes.

### CODE REVIEW

**Comment by dominiksalvet** [comment]
Hi @agura-lex, normally I would assign you as a reviewer as more eyes see more, but I need to merge this PR really quickly and continue with work on 3.0.0 release. I still need to fit some features in the release. Please, take a look at the [3.0.0 project](https://github.com/dominiksalvet/asus-fan-control/projects/1).

In case of any critical comments on this PR, feel free to post them even after merging this PR. I will certainly take them into account and include them into master.

**Comment by agura-lex** [comment]
I thought about adding revert/stop feature which will revert to vendor temps without a reboot. But I think we can add it to 3.1. 

The idea is simple: prior to enabling new temps, asus-fan-control gets current temps and writes them to some place in `/tmp/` if they're not already written. And when issuing something like "revert-temps" it'll revert temps to the values stored in `/tmp`. BTW, it will allow making systemd service stoppable by adding smth like `ExecStop=/usr/local/bin/asus-fan-control revert-temps`.

**Comment by agura-lex** [comment]
I can make a PR when you're done with all other changes.

**Comment by dominiksalvet** [comment]
@agura-lex Thank you for the suggestion but I am strongly against it. The very reason that asus-fan-control exists is exactly due to bad vendor temperatures. I am not interested in this feature and I think that almost none of the asus-fan-control end users would be.

Yeah, there is the thing with stopping the systemd service, I must admit, but we must keep in mind that we use systemd and not that systemd uses us...

There is another important thing. Keep in mind that using ACPI is not the same as using memory. Meaning that ACPI may have some side effects behind the interface, which we are not able to observe. Then, reverting the ACPI state would implies that we know exactly how things work on the other side of the ACPI interface, which is not true (at least for me).

Does it make sense? :-)

**Comment by dominiksalvet** [comment]
@agura-lex I released the [3.0.0](https://github.com/dominiksalvet/asus-fan-control/releases/tag/3.0.0) version yesterday and I have been thinking a bit. Once you get to update the AUR package, please can you do something more...? Explained below. :arrow_down: 

As asus-fan-control has slowly reached the point that **I am quite satisfied with it**, it would not be a bad idea to promote it somehow so that more people can find it. If you have permissions to edit the [Fan speed control page](https://wiki.archlinux.org/index.php/Fan_speed_control) on ArchWiki, it would be the best place to introduce asus-fan-control as a simple Shell-based fan controller. Otherwise, it seems that ASUS users have to use kernel modules to approach the same effect as with asus-fan-control (which uses only quite known acpi_call module), which is very convenient.

If you also consider that thanks to you asus-fan-control may be installed directly from AUR, it will fit in ArchWiki very well I think. What do you think about it? :smile: :rocket: 

---

I do not hurry, take your time... :smile:

**Comment by agura-lex** [comment]
Hello, yeah, I was going to add it to the article since discovered it, lol. But somewhat wasn't sure how to approach it. I even started editing but rebooted my laptop and lost all the progress. :D 

But that's a good idea, I'll add it to the article when I have enough time to. :rocket:

**Comment by dominiksalvet** [comment]
@agura-lex Glad to hear that! Certainly let me know when you do so... :smile:

**Comment by dominiksalvet** [comment]
Hello @agura-lex! :wave: How are you doing? :smile: 

I just wanted to ask about adding asus-fan-control to ArchWiki. Would you be able to do it in the foreseeable future? It would be so epic! :gem: 

> Did you know that we have a [community-driven Wiki](https://github.com/dominiksalvet/asus-fan-control/wiki) created by @Greifent?

**Comment by agura-lex** [comment]
Hey man, what's up! Thanks, doing great, but it's very busy time for me lately, and unfortunately I don't think I'll be able to edit that ArchWiki article soon. Yeah, I saw there's a wiki now, haven't visited it yet though.

**Comment by dominiksalvet** [comment]
Glad to hear that you are doing great! :smile: About the ArchWiki -- feel free to do it as soon as you have time. I just wanted to know that you are still on GitHub... :octocat:

It is asus-fan-control's future potential to grow. So it will make me happy anytime it will arrive! :rocket: There has been a lot of improvements since you were here last time - [afc-scout](https://github.com/dominiksalvet/afc-scout), [wiki](https://github.com/dominiksalvet/asus-fan-control/wiki), [afc-gui](https://github.com/Greifent/afc-gui), [support for dual fans](https://github.com/dominiksalvet/asus-fan-control/issues/38). So yeah, we definitely have something to offer! :clap:

> I understand that you are busy but I still wanted to provide the links in case you are interested so that you would know directly where to go. :tada:

See you later and thank you for the info! :wave:

**Pull request merged**
